// Extrait de RECETTES.html

// ===================== DONNÉES RECETTES =====================
  const recipes = [
    { title: "Wraps", sub: "Repas complet · rapide", icon: "🌯", iconColor: "orange", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Galette · steak haché · oignons · poivrons · tomates cerises · galette de pomme de terre · cornichons aigre-doux<br><em>Option : salade, tomate en tranche</em>" }, { label: "Sauces & épices", val: "Fromage à tartiner · mayo, ketchup, sauce épicée · sauce soja sucrée-salée · paprika · sésame · curry rouge" }], steps: ["Tartiner la galette de fromage à tartiner, mayo, ketchup et sauce épicée. Disposer les tomates cerises coupées et les cornichons. Saupoudrer de sésame.", "Dans une poêle, faire revenir oignons, poivrons et steak haché en morceaux. Ajouter les épices et la sauce soja en cours de cuisson.", "Rassembler le tout sur la galette, rouler et déguster."] },
    { title: "Sandwich", sub: "Classique maison · rapide", icon: "🥪", iconColor: "vert", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Pain de mie · fromage à tartiner · fromage en tranche · mayo, ketchup, sauce épicée · protéine (jambon, poulet, dinde)<br><em>Option : cornichons, salade, tomate</em>" }, { label: "Montage", val: "Tranche 1 : fromage à tartiner. Tranche 2 : sauces + fromage en tranche + cornichons + protéine pliée. Refermer et déguster." }] },
    { title: "Burger", sub: "Complet · montage soigné", icon: "🍔", iconColor: "orange", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Buns briochés · protéine (steak haché, pulled pork, poulet pané) · galette de pomme de terre · bacon · oignons · cornichons · fromage à tartiner · cheddar ou emmental · mayo, ketchup, sauce épicée" }, { label: "Montage", val: "Toaster les buns. Tartiner un côté de fromage à tartiner, l'autre de sauces. Disposer fromage en tranche + cornichons. Ajouter les ingrédients chauds." }] },
    { title: "Chili", sub: "Mijoté · pour 2–3 personnes", icon: "🍲", iconColor: "fruit", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "Riz · haricots rouges · maïs · poivrons · carottes · oignon · protéine · sauce tomate · paprika, sésame, curry rouge" }, { label: "Préparation", val: "Cuire le riz (7 min). Cuire les haricots (30 min). Faire revenir oignon + protéine + poivrons + épices. Mélanger avec haricots + sauce tomate. Mijoter. Ajouter le maïs. Servir avec le riz." }] },
    { title: "Couscous", sub: "Simple et rapide", icon: "🫕", iconColor: "vert", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Semoule · boîte de légumes à couscous · protéine (steak haché ou hauts de cuisse)" }, { label: "Préparation", val: "Cuire la semoule à l'eau chaude avec du beurre. Cuire les légumes en casserole. Cuire la protéine à part. Assembler une fois tout cuit." }] },
    { title: "Pâtes à la bolognaise", sub: "Le classique du quotidien", icon: "🍝", iconColor: "orange", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Pâtes · oignon · protéine · sauce tomate<br><em>Option : poivron, carotte, paprika, sésame, curry rouge</em>" }, { label: "Préparation", val: "Cuire les pâtes (7 min). Faire revenir oignon + protéine + poivrons + épices. Ajouter sauce tomate, mijoter. Incorporer les pâtes et mélanger." }] },
    { title: "Lentilles saucisses", sub: "Mijoté réconfortant", icon: "🍲", iconColor: "vert", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "Lentilles · saucisses à cuire · oignon<br><em>Option : carottes</em>" }, { label: "Préparation", val: "Cuire les lentilles (et carottes). Cuire les saucisses. Faire revenir l'oignon. Tout ajouter aux lentilles et laisser mijoter." }] },
    { title: "Hauts de cuisses miel-moutarde", sub: "Four 200°C · 30 min", icon: "🍗", iconColor: "orange", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "4 hauts de cuisses · 2 c.à.s moutarde · 2 c.à.s miel · 1 c.à.s huile d'olive · sel, poivre<br><em>Option : herbes de Provence, ail en poudre</em>" }, { label: "Préparation", val: "Mélanger miel + moutarde + huile. Saler, poivrer les hauts de cuisses, badigeonner de sauce. Enfourner 200°C, 30 min en arrosant à mi-cuisson." }] },
    { title: "Haricots verts au beurre de cacahuète", sub: "Saveurs asiatiques · 20 min", icon: "🥜", iconColor: "fruit", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "200 g haricots verts · 2 blancs de poulet · 1 verre riz · 2 c.à.s beurre de cacahuète · 1 c.à.s sauce soja · 1 c.à.s miel · 1 gousse d'ail · huile<br><em>Option : sésame, coriandre, citron vert, piment</em>" }, { label: "Sauce cacahuète", val: "Mélanger beurre de cacahuète + sauce soja + miel + ail + un peu d'eau chaude pour fluidifier. Verser dans la poêle avec le poulet, ajouter les haricots, chauffer 2 min." }] },
    { title: "Nouilles japonaises aux champignons", sub: "Bouillon réconfortant", icon: "🍜", iconColor: "violet", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Nouilles japonaises · œuf · champignons · bouillon de poulet" }, { label: "Préparation", val: "Faire revenir les champignons. Cuire les nouilles dans le bouillon. Faire l'œuf mollet à part. Assembler dans un bol." }] },
    { title: "Nouilles instantanées à l'œuf", sub: "Rapide · 5 min", icon: "🍜", iconColor: "orange", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "1 sachet nouilles instantanées · 1 œuf · 400 ml eau<br><em>Option : sauce soja, ciboulette, légumes, huile de sésame</em>" }, { label: "Préparation", val: "Bouillir l'eau, ajouter nouilles + épices. Après 2 min, casser l'œuf (poché entier ou en filet battu). Cuire encore 1–2 min. Servir chaud." }] },
    { title: "Mac & Cheese revisité", sub: "Anti-gaspi · avec des restes de pâtes", icon: "🧀", iconColor: "vert", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Restes de pâtes · crème fraîche · gruyère râpé · cheddar · fromage à tartiner (optionnel) · lardons · ½ oignon rouge · oignons frits · sel, poivre, paprika<br><em>Option : sauce volcano</em>" }, { label: "Sauce fromagère", val: "À feu doux : crème + gruyère + cheddar + fromage à tartiner. Saler, poivrer. Ajouter lardons + oignons dorés. Incorporer les pâtes. Option gratin : grill 5–7 min." }] },
    { title: "Hachis Parmentier", sub: "Four 200°C · gratiner 15 min", icon: "🥔", iconColor: "fruit", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "500 g pommes de terre · 300 g viande hachée · 1 oignon · 50 ml lait · fromage râpé · sel, poivre, muscade" }, { label: "Préparation", val: "Cuire et écraser les pommes de terre en purée. Faire revenir oignon + viande. Plat : viande au fond → purée → fromage râpé. Gratiner 15 min à 200°C." }] },
    { title: "Floraline au jambon", sub: "Réconfortant · 10 min", icon: "🥣", iconColor: "vert", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "2 c.à.s Floraline · 200–250 ml lait · 1 tranche jambon en morceaux · sel, poivre<br><em>Option : fromage râpé, œuf, herbes</em>" }, { label: "Préparation", val: "Chauffer le lait. Verser la Floraline en pluie en mélangeant. Cuire 2–3 min à feu doux jusqu'à épaississement. Ajouter le jambon, assaisonner." }] },
    { title: "La soupe", sub: "Légumes de saison · 30 min", icon: "🥣", iconColor: "orange", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "2 carottes · 2 pommes de terre · 1 navet · 1 poireau · 1 oignon · 1 cube de bouillon · 1 L eau · sel, poivre" }, { label: "Préparation", val: "Faire revenir l'oignon, ajouter les légumes coupés, couvrir de 1 L eau + cube de bouillon. Porter à ébullition, mijoter 25 min. Mixer (ou non)." }] },
    { title: "La salade", sub: "Base modulable à l'infini", icon: "🥗", iconColor: "violet", type: "sale", time: ["rapide"], blocks: [{ label: "Base", val: "Salade découpée · tomate · oignon · feta · sauce crudité + sauce relevée" }, { label: "Options", val: "Avocat · croutons · pâtes/pomme de terre · cornichons · carotte · radis · poivron · lardons, poulet, thon, viande hachée…" }], note: "Juste tout mélanger !" },
    { title: "Brunch", sub: "Week-end · tout en un", icon: "🥚", iconColor: "vert", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Œufs · bacon<br><em>Option : saucisse, galette de pomme de terre, yaourt + chia, pain de mie avec fromage à tartiner ou avocat</em>" }, { label: "Préparation", val: "Faire les œufs brouillés. Faire cuire le bacon. Tout mettre ensemble dans une belle assiette." }] },
    { title: "Pistou maison", sub: "Basilic du balcon — soupe, pâtes, tartines", icon: "🌿", iconColor: "vert", type: "sale", time: ["rapide", "mealprep"], blocks: [{ label: "Ingrédients", val: "1 grosse poignée basilic frais · 1 gousse d'ail · 4 c.à.s huile d'olive · sel" }, { label: "Préparation", val: "Mixer ou piler au mortier basilic + ail + sel. Incorporer l'huile progressivement. Conserver au frigo recouvert d'un filet d'huile." }], note: "Récolter juste avant de préparer pour un arôme maximal. Se congèle très bien en cubes dans un bac à glaçons." },
    { title: "Gremolata persil & citron", sub: "Condiment vif — poisson, légumes, risotto", icon: "🥗", iconColor: "fruit", type: "sale", time: ["rapide", "mealprep"], blocks: [{ label: "Ingrédients", val: "1 bouquet persil frisé · zeste d'1 citron bio · 1 gousse d'ail · sel" }, { label: "Préparation", val: "Hacher finement persil + ail. Mélanger avec le zeste de citron + sel. Parsemer au dernier moment sur le plat chaud." }], note: "Se prépare minute — elle perd vite son arôme. Idéale sur un osso-buco, des carottes rôties ou un simple riz vapeur." },
    { title: "Huile infusée thym & romarin", sub: "Condiment de base — infusion 2 semaines", icon: "🌿", iconColor: "orange", type: "sale", time: ["long", "mealprep"], blocks: [{ label: "Ingrédients", val: "6 brins thym frais · 2 brins romarin · 250 ml huile d'olive" }, { label: "Préparation", val: "Laver et sécher parfaitement les herbes. Placer dans une bouteille propre. Verser l'huile. Infuser 2 semaines à l'abri de la lumière." }], note: "Les herbes doivent être parfaitement sèches — une seule goutte d'eau peut créer de la moisissure." },
    { title: "Beurre composé aux herbes", sub: "Sur un poisson, une viande grillée, à tartiner", icon: "🧄", iconColor: "vert", type: "sale", time: ["long", "mealprep"], blocks: [{ label: "Ingrédients", val: "125 g beurre mou · 3 feuilles verveine · 5 feuilles menthe · 2 brins thym effeuillé · sel, poivre" }, { label: "Préparation", val: "Ciseler finement les herbes. Mélanger au beurre mou. Rouler dans du film alimentaire en boudin. Réfrigérer 2h. Couper en rondelles." }], note: "Se congèle très bien. Lavande + citron pour le poisson, thym + ail pour la viande." },
    { title: "Taboulé à la menthe & persil", sub: "Pour 4 personnes · 20 min", icon: "🥗", iconColor: "orange", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "200 g semoule fine · 1 grosse poignée menthe verte fraîche · 1 poignée persil frisé · 3 tomates · 1 citron · huile d'olive" }, { label: "Préparation", val: "Verser de l'eau bouillante sur la semoule, couvrir 5 min, égrainer. Couper les tomates, ciseler les herbes. Assaisonner avec citron et huile." }], note: "Ajouter les herbes au dernier moment pour garder leur couleur vive." },
    { title: "Noix activées & torréfiées", sub: "Snack sain — meilleure digestion, goût sublime", icon: "🌰", iconColor: "orange", type: "sale", time: ["long", "mealprep"], blocks: [{ label: "Étape 1 — Trempage", val: "Couvrir d'eau froide + ½ c.à.c de sel par bol.<br><strong>Amandes</strong> 12h · <strong>Noix</strong> 8h · <strong>Cajou</strong> 4–6h · <strong>Noisettes</strong> 8h · <strong>Macadamia</strong> 4h · <strong>Tournesol</strong> 2h" }, { label: "Étape 2 — Torréfaction", val: "Rincer, sécher. Four à basse t°.<br><strong>Amandes</strong> 160°C 12–15 min · <strong>Noix</strong> 160°C 10–12 min · <strong>Cajou</strong> 160°C 8–10 min · <strong>Noisettes</strong> 170°C 12 min" }], note: "Snack express : noix torréfiées + huile d'olive + paprika fumé + sel. 10 min au four à 160°C.", potInfo: "Conservation : bocal hermétique. Activées non torréfiées : frigo 3–4 jours. Torréfiées : 2–3 semaines." },
    { title: "Flageolets aux lardons", sub: "Simple et nourrissant · 35 min", icon: "🫘", iconColor: "fruit", type: "sale", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Flageolets (boîte ou secs) · lardons · oignon · sel, poivre<br><em>Option : bouillon, herbes de Provence, moutarde</em>" }, { label: "Temps", val: "Flageolets en boîte : 15 min<br>Flageolets secs : tremper 12h, cuire 1h30" }], steps: ["Cuire les flageolets (en boîte : égoutter et rincer. Secs : tremper une nuit puis cuire 1h30).", "Dans une poêle, faire revenir les lardons à sec jusqu'à dorure. Ajouter l'oignon émincé, 3–4 min.", "Ajouter les flageolets. Mélanger, mijoter 5–10 min à feu doux. Saler légèrement, poivrer."], note: "Une cuillerée de moutarde à l'ancienne en fin de cuisson change tout." },
    { title: "Pâte pour petit pain", sub: "Classique maison · repos 1h minimum", icon: "🍞", iconColor: "fruit", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "250g farine · 100ml eau chaude · 100ml huile d'olive · levure chimique · 1 c.à.c sel<br><em>Option salé : épices — Option sucré : sucre</em>" }, { label: "Montage", val: "Mélanger tous les ingrédients énergiquement. Laisser reposer 30 min à 1h. Étaler et cuire à la poêle (effet wrap) ou à l'air fryer." }], note: "À l'air fryer : pré-cuire la pâte pour qu'elle soit cuite entièrement.", potInfo: "Épices à ajouter : paprika, herbes de Provence, origan, piment de Cayenne." },
    { title: "Bouchée du diable", sub: "2 ingrédients · 1 minute", icon: "😈", iconColor: "orange", type: "sucre", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "Pain de mie · pâte à tartiner au chocolat · beurre de cacahuète" }, { label: "Préparation", val: "Tartiner une tranche de pâte à tartiner. L'autre de beurre de cacahuète. Assembler les deux. Déguster." }] },
    { title: "Tiramisu", sub: "Pour 4–6 personnes · repos 4h minimum", icon: "☕", iconColor: "violet", type: "sucre", time: ["long"], blocks: [{ label: "Ingrédients", val: "3 œufs · biscuits cuillère · 250 g mascarpone · 70 g sucre · café · cacao en poudre" }, { label: "Méthode", val: "Fouetter jaunes + sucre jusqu'à blanchissement. Ajouter mascarpone. Monter les blancs en neige, incorporer délicatement. Tremper les biscuits dans le café. Alterner couches biscuits/crème. Cacao sur le dessus. 4h au frigo minimum." }] },
    { title: "Mugcake au chocolat", sub: "1 mug · 1 min 30 au micro-ondes", icon: "🍫", iconColor: "orange", type: "sucre", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "3 c.à.s farine · 2 c.à.s sucre · 2 c.à.s cacao non sucré · 1 œuf · 2 c.à.s lait · 2 c.à.s huile neutre<br><em>Option : pépites, noisettes, vanille</em>" }, { label: "Préparation", val: "Mélanger farine + sucre + cacao dans un mug. Ajouter l'œuf, battre. Ajouter lait + huile. Micro-ondes 1 min à 1 min 30. Laisser tiédir 1 min." }] },
    { title: "Cookies", sub: "Four 180°C · 10 min · ~15 cookies", icon: "🍪", iconColor: "vert", type: "sucre", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "100 g beurre mou · 100 g sucre · 1 œuf · 150 g farine · ½ sachet levure · 100 g pépites de chocolat<br><em>Option : noix, vanille, zestes, fruits secs</em>" }, { label: "Préparation", val: "Mélanger beurre + sucre. Ajouter l'œuf. Verser farine + levure. Incorporer pépites. Former des boules sur plaque. Cuire 10 min à 180°C. Laisser refroidir 5 min." }], note: "Ils paraissent encore mous à la sortie du four — c'est normal, ils durcissent en refroidissant !" },
    { title: "Fraises gariguette & verveine", sub: "Dessert minute · 10 min", icon: "🍓", iconColor: "orn", type: "sucre", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "500 g fraises gariguette · 4 feuilles verveine fraîche · 1 c.à.s sucre ou miel · jus ½ citron" }, { label: "Préparation", val: "Couper les fraises en deux. Ciseler la verveine très finement. Mélanger avec sucre et citron. Macérer 15 min avant de servir." }], note: "Servir avec une boule de glace vanille ou du yaourt grec." },
    { title: "Panna cotta à la lavande", sub: "Pour 4 · veille au frigo", icon: "💜", iconColor: "violet", type: "sucre", time: ["long"], blocks: [{ label: "Ingrédients", val: "500 ml crème liquide · 50 g sucre · 3 tiges lavande fraîche · 2 feuilles gélatine (ou 1 c.à.c agar-agar)" }, { label: "Préparation", val: "Infuser la lavande dans la crème chaude 10 min. Filtrer. Ajouter sucre + gélatine ramollie. Verser en ramequins. Réfrigérer 4h minimum." }], note: "Doser la lavande avec parcimonie — trop forte, elle donne un goût savonneux." },
    { title: "Crumble framboises & menthe", sub: "Pour 4 · 35 min · four 180°C", icon: "🫐", iconColor: "fruit", type: "sucre", time: ["long"], blocks: [{ label: "Ingrédients", val: "300 g framboises · 6 feuilles menthe · 80 g farine · 60 g beurre froid · 50 g cassonade · 40 g poudre d'amande" }, { label: "Préparation", val: "Framboises + menthe ciselée dans un plat. Sabler farine + beurre froid + cassonade + amande du bout des doigts. Répartir sur les fruits. Cuire 25 min à 180°C." }] },
    { title: "Sirop de verveine", sub: "Boissons, desserts, cocktails — conserve 3 mois", icon: "🍯", iconColor: "orange", type: "conserves", time: ["rapide", "mealprep"], blocks: [{ label: "Ingrédients", val: "1 grosse poignée verveine fraîche · 300 g sucre · 300 ml eau · jus d'1 citron" }, { label: "Préparation", val: "Porter eau + sucre à ébullition. Retirer du feu, ajouter la verveine. Couvrir, infuser 20 min. Filtrer, ajouter le citron. Mettre en bouteille stérilisée." }], note: "Le citron est conservateur naturel et fixe la couleur verte." },
    { title: "Sel aromatisé maison", sub: "Condiment — conserve 6 mois", icon: "🫙", iconColor: "violet", type: "conserves", time: ["long", "mealprep"], blocks: [{ label: "Ingrédients", val: "200 g gros sel · 4 brins thym · 2 brins romarin · 1 brin lavande · zeste citron (optionnel)" }, { label: "Préparation", val: "Effeuiller les herbes, sécher 1h à 50°C. Mixer grossièrement avec le sel. Étaler, sécher 24h à l'air. Mettre en bocal." }], note: "Parfait sur légumes grillés, poisson ou beurre. En petit pot, c'est un très beau cadeau fait maison." },
    { title: "Confiture fraises & menthe", sub: "2 pots · conserve 1 an", icon: "🍓", iconColor: "fruit", type: "conserves", time: ["long", "mealprep"], blocks: [{ label: "Ingrédients", val: "500 g fraises gariguette · 350 g sucre à confiture · jus d'1 citron · 8 feuilles menthe fraîche" }, { label: "Préparation", val: "Macérer fraises + sucre + citron 1h. Cuire 20 min en remuant. Ajouter la menthe les 2 dernières min. Pots stérilisés, retourner jusqu'au refroidissement." }], note: "Test de prise : une goutte sur assiette froide doit gélifier en quelques secondes." },
    { title: "Eau infusée menthe & concombre", sub: "Rafraîchissant · à préparer la veille", icon: "🥤", iconColor: "vert", type: "boissons", time: ["long", "mealprep"], blocks: [{ label: "Ingrédients (1 litre)", val: "8 feuilles menthe ananas · ½ concombre en tranches fines · 1 litre eau froide · glaçons" }, { label: "Méthode", val: "Placer tous les ingrédients dans une carafe. Infuser 4h minimum au réfrigérateur. Servir bien frais." }] },
    { title: "Limonade verveine & fraises", sub: "Pour 4 personnes · 15 min", icon: "🧃", iconColor: "orange", type: "boissons", time: ["rapide"], blocks: [{ label: "Ingrédients", val: "200 g fraises · 6 feuilles verveine · jus de 2 citrons · 2 c.à.s miel · 750 ml eau gazeuse" }, { label: "Méthode", val: "Mixer fraises + verveine + citron + miel. Filtrer si désiré. Verres avec glace, compléter d'eau gazeuse. Décorer d'une feuille de verveine." }] },
    { title: "Mocktail lavande & citron", sub: "Élégant · sans alcool", icon: "🫧", iconColor: "violet", type: "boissons", time: ["rapide"], blocks: [{ label: "Ingrédients (1 verre)", val: "2 c.à.s sirop de lavande (ou verveine) · jus ½ citron · eau gazeuse · glaçons · 1 tige lavande" }, { label: "Méthode", val: "Sirop + citron dans un verre sur glace. Compléter d'eau gazeuse. Remuer doucement. Décorer d'une tige de lavande." }] },
  { title: "Pommes de terre sautées", sub: "Dorées et croustillantes à la poêle", icon: "🥔", iconColor: "orange", type: "sale", time: ["moyen"], blocks: [{ label: "Ingrédients", val: "Pommes de terre · huile · beurre · ail · persil<br><em>Option : thym, oignon, paprika</em>" }, { label: "Préparation", val: "Couper en dés, rincer, sécher. Précuire 5 min à l'eau (optionnel). Faire sauter à feu vif sans bouger 4-5 min. Ajouter beurre + ail, continuer 8-10 min en remuant jusqu'à dorure. Saler, parsemer de persil." }] },

{ title: "Pommes de terre rôties", sub: "Croustillantes à l'air fryer", icon: "🥔", iconColor: "yellow", type: "sale", time: ["moyen"], blocks: [{ label: "Ingrédients", val: "Pommes de terre · huile d'olive · paprika fumé · ail en poudre · herbes de Provence<br><em>Option : romarin, cumin, parmesan</em>" }, { label: "Préparation", val: "Couper en quartiers, sécher. Enrober d'huile et d'épices. Air fryer 200°C : 15 min, secouer, puis 8-10 min jusqu'à dorure. Servir immédiatement." }] },

{ title: "Purée maison", sub: "Onctueuse et réconfortante", icon: "🥣", iconColor: "yellow", type: "sale", time: ["moyen"], blocks: [{ label: "Ingrédients", val: "Pommes de terre farineuses · lait entier · beurre · noix de muscade<br><em>Option : crème fraîche, gruyère, ciboulette</em>" }, { label: "Préparation", val: "Cuire les pommes de terre 20 min à l'eau salée. Égoutter. Écraser au presse-purée avec le beurre. Ajouter le lait chaud petit à petit jusqu'à consistance souhaitée. Assaisonner." }] },

{ title: "Frites maison", sub: "Légères et croustillantes à l'air fryer", icon: "🍟", iconColor: "yellow", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "Pommes de terre · huile · sel<br><em>Option : paprika, ail en poudre, herbes</em>" }, { label: "Préparation", val: "Couper en bâtonnets, tremper 30 min dans l'eau froide, bien sécher. Enrober d'huile. Air fryer 180°C pendant 15 min, secouer. Monter à 200°C pour 5-8 min. Saler à la sortie." }] },

{ title: "Pommes de terre lyonnaises", sub: "Le classique aux oignons dorés", icon: "🧅", iconColor: "orange", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "Pommes de terre · oignons · beurre · huile · persil<br><em>Option : lardons, thym, vinaigre de vin</em>" }, { label: "Préparation", val: "Précuire les pommes de terre entières 20 min, laisser refroidir, couper en rondelles. Faire dorer les oignons 10 min. Faire revenir les rondelles 3-4 min de chaque côté. Mélanger, assaisonner, parsemer de persil." }] },

{ title: "Robe des champs", sub: "Un repas complet à l'air fryer", icon: "🥔", iconColor: "brown", type: "sale", time: ["long"], blocks: [{ label: "Ingrédients", val: "Grosses pommes de terre · huile d'olive · gros sel · crème fraîche · ciboulette<br><em>Option : fromage râpé, thon mayo, chili</em>" }, { label: "Préparation", val: "Piquer les pommes de terre, badigeonner d'huile, frotter de gros sel. Air fryer 200°C pendant 35-40 min. Inciser en croix, garnir de crème fraîche et ciboulette." }] },
  ];

  // ===================== DONNÉES TISANES =====================
  const tisanes = [
    { cat: "methode", effet: [], badge: "Méthode", badgeClass: "badge-mel", title: "Récolter frais ou sécher", sub: "Étape 1", desc: "Frais : 1 grosse poignée de feuilles ou fleurs pour 25 cl. Sec : 1 cuillère à soupe rase. Sécher à l'ombre, dans un endroit aéré, 1 à 2 semaines.", note: null, warn: null },
    { cat: "methode", effet: [], badge: "Méthode", badgeClass: "badge-mel", title: "Eau à la bonne température", sub: "Étape 2", desc: "Herbes délicates (verveine, menthe, camomille) : 85–90 °C, jamais à gros bouillon. Thym, lavande : 95 °C possible.", note: "L'eau bouillante détruit les huiles essentielles des plantes fragiles.", warn: null },
    { cat: "methode", effet: [], badge: "Méthode", badgeClass: "badge-mel", title: "Infuser couvert", sub: "Étape 3", desc: "Toujours couvrir la tasse ou la théière pendant l'infusion : les principes actifs volatils s'évaporent sinon. Durée : 5 à 10 min selon la plante.", note: null, warn: null },
    { cat: "methode", effet: [], badge: "Méthode", badgeClass: "badge-mel", title: "Filtrer et boire", sub: "Étape 4", desc: "Filtrer, laisser tiédir si besoin. On peut sucrer avec du miel ajouté après refroidissement à 40 °C pour préserver ses enzymes.", note: "Éviter le sucre blanc qui neutralise certains effets.", warn: null },
    { cat: "methode", effet: [], badge: "Méthode", badgeClass: "badge-mel", title: "Fréquence et durée de cure", sub: "Étape 5", desc: "1 à 3 tasses par jour pour un effet thérapeutique. En cure de 2 à 3 semaines, puis pause.", note: null, warn: "Les tisanes quotidiennes sans pause peuvent fatiguer le foie ou créer une accoutumance. Les tisanes médicinales ne remplacent pas un avis médical." },
    { cat: "solo", effet: ["stress","digestif","sommeil"], badge: "Plante seule", badgeClass: "badge-med", title: "Verveine citronnelle", sub: "Détente, digestion", dosage: "5–6 grandes feuilles", infusion: "88 °C — 8 min, couvert", note: "La plus agréable en goût. Idéale le soir après un repas chargé ou avant le coucher.", warn: null },
    { cat: "solo", effet: ["sommeil","digestif"], badge: "Plante seule", badgeClass: "badge-med", title: "Camomille allemande", sub: "Anti-inflammatoire, crampes, sommeil", dosage: "1 grosse poignée de fleurs", infusion: "85 °C — 5 min max, couvert", note: "Ne pas dépasser 5 min : au-delà l'infusion devient amère. Fleurs fraîches ou séchées, les deux fonctionnent.", warn: null },
    { cat: "solo", effet: ["immunite","digestif","froid"], badge: "Plante seule", badgeClass: "badge-med", title: "Thym commun", sub: "Antiseptique, toux, digestion", dosage: "2–3 brins (feuilles + tiges)", infusion: "95 °C — 8–10 min, couvert", note: "Ajouter un filet de citron et du miel pour démultiplier l'effet antiseptique.", warn: null },
    { cat: "solo", effet: ["digestif"], badge: "Plante seule", badgeClass: "badge-med", title: "Menthe verte ou ananas", sub: "Digestive, fraîche, nausées", dosage: "6–8 feuilles", infusion: "85 °C — 5–7 min, couvert", note: "La menthe ananas est plus douce et sucrée, idéale nature. Excellentes froides aussi (cold brew 4h au frigo).", warn: null },
    { cat: "solo", effet: ["sommeil","stress"], badge: "Plante seule", badgeClass: "badge-med", title: "Lavande grosso", sub: "Anxiété, maux de tête, sommeil", dosage: "3–4 tiges fleuries", infusion: "90 °C — 5–7 min, couvert", note: "Le lavandin 'Grosso' est plus camphrée que la vraie lavande fine. Se marie bien avec la verveine pour adoucir.", warn: null },
    { cat: "solo", effet: ["detox"], badge: "Plante seule", badgeClass: "badge-med", title: "Feuilles de fraisier & framboisier", sub: "Astringente, dépurative, tonique", dosage: "4–5 feuilles jeunes", infusion: "90 °C — 10 min, couvert", note: "Goût légèrement tannique : à associer avec menthe ou verveine.", warn: "Feuilles de framboisier déconseillées en début de grossesse." },
    { cat: "solo", effet: ["digestif","stress"], badge: "Plante seule", badgeClass: "badge-med", title: "Basilic grand vert", sub: "Digestif, antispasmodique, anti-stress léger", dosage: "6–8 grandes feuilles", infusion: "85 °C — 5 min, couvert", note: "Ne jamais faire bouillir. Goût doux et légèrement anisé. Se marie bien avec la verveine ou la menthe.", warn: null },
    { cat: "solo", effet: ["detox"], badge: "Plante seule", badgeClass: "badge-med", title: "Persil frisé", sub: "Reminéralisant, diurétique doux, dépuratif", dosage: "1 petite poignée de feuilles et tiges", infusion: "90 °C — 8 min, couvert", note: "Goût herbacé assez prononcé — adoucir avec de la menthe ou du miel.", warn: "Déconseillé en tisane concentrée pendant la grossesse." },
    { cat: "melange", effet: ["sommeil","stress"], badge: "Mélange", badgeClass: "badge-imm", title: "Nuit douce", sub: "Sommeil, détente profonde", dosage: "3 feuilles verveine + 1 poignée fleurs camomille + 2 tiges lavande", infusion: "88 °C — 7 min couvert — miel possible", note: "Le trio classique des herboristes contre l'insomnie légère. Boire 30 min avant le coucher.", warn: null },
    { cat: "melange", effet: ["digestif"], badge: "Mélange", badgeClass: "badge-imm", title: "Après repas digestif", sub: "Ballonnements, lourdeurs, crampes", dosage: "4 feuilles menthe verte + 3 feuilles verveine + 1 brin thym (optionnel)", infusion: "88 °C — 6 min couvert", note: "Boire chaud, 10 min après le repas.", warn: null },
    { cat: "melange", effet: ["immunite","froid"], badge: "Mélange", badgeClass: "badge-imm", title: "Défenses hivernales", sub: "Rhume, gorge, bronchites", dosage: "3 brins thym + 1 poignée camomille + jus ½ citron + miel", infusion: "95 °C — 10 min couvert — citron + miel après", note: "3 tasses par jour en phase aiguë.", warn: null },
    { cat: "melange", effet: ["detox"], badge: "Mélange", badgeClass: "badge-imm", title: "Cure dépurative printanière", sub: "Détox douce, reminéralisation", dosage: "3 feuilles fraisier + 3 feuilles framboisier + 3 feuilles menthe", infusion: "90 °C — 10 min couvert — 2–3 semaines de cure", note: "Idéale au printemps. Goût doux si on ajoute la menthe.", warn: "Déconseillée en début de grossesse (feuilles de framboisier)." },
    { cat: "melange", effet: ["digestif","stress"], badge: "Mélange", badgeClass: "badge-imm", title: "Fraîcheur estivale", sub: "Désaltérante, légère (froide ou chaude)", dosage: "8 feuilles menthe ananas + 4 feuilles verveine + 2 tiges lavande", infusion: "Cold brew : eau froide, 4–6h au frigo — ou infusion chaude puis refroidie", note: "En cold brew, les arômes sont plus doux et floraux.", warn: null },
    { cat: "moment", effet: ["immunite","froid"], badge: "Moment", badgeClass: "badge-ete", title: "Matin — réveil en douceur", sub: "Pour bien démarrer", desc: "Thym + citron + miel pour démarrer la journée. Ou menthe verte seule si le matin est frais.", note: null, warn: null },
    { cat: "moment", effet: ["digestif"], badge: "Moment", badgeClass: "badge-ete", title: "Après déjeuner — digestion", sub: "En fin de repas", desc: "Menthe verte + verveine. Le duo le plus courant en France après le repas.", note: null, warn: null },
    { cat: "moment", effet: ["stress"], badge: "Moment", badgeClass: "badge-ete", title: "Après-midi — pause anti-stress", sub: "Pour couper le rythme", desc: "Verveine seule ou avec camomille. Légère, sans caféine, idéale pour couper le rythme.", note: null, warn: null },
    { cat: "moment", effet: ["sommeil"], badge: "Moment", badgeClass: "badge-ete", title: "Soir — préparation au sommeil", sub: "30–45 min avant de se coucher", desc: "Camomille + lavande + verveine. Le trio nuit douce.", note: null, warn: null },
    { cat: "moment", effet: ["immunite","froid"], badge: "Moment", badgeClass: "badge-ete", title: "En cas de rhume", sub: "Dès les premiers symptômes", desc: "Thym + camomille + miel + citron. 3 tasses par jour.", note: null, warn: null },
    { cat: "moment", effet: ["digestif"], badge: "Moment", badgeClass: "badge-ete", title: "En été — froide", sub: "Cold brew à préparer la veille", desc: "Menthe ananas + verveine en cold brew. Préparer le soir, boire le lendemain.", note: null, warn: null }
  ];

  // ===================== ÉTAT =====================
  let section = 'recettes';
  let activeType = 'all', activeTime = 'all';
  let activeTCat = 'all', activeTEffet = 'all';

  // ===================== SECTION =====================
  function setSection(s, btn) {
    section = s;
    document.querySelectorAll('.section-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('filters-recettes').style.display = s === 'recettes' ? 'flex' : 'none';
    document.getElementById('filters-tisanes').style.display  = s === 'tisanes'  ? 'flex' : 'none';
    render();
  }

  // ===================== FILTRES RECETTES =====================
  function filterType(type, btn) {
    activeType = type;
    document.querySelectorAll('.filter-btn:not(.time-btn):not(.section-btn)').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    render();
  }
  function filterTime(time, btn) {
    activeTime = time;
    document.querySelectorAll('.time-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    render();
  }

  // ===================== FILTRES TISANES =====================
  function filterTCat(cat, btn) {
    activeTCat = cat;
    document.querySelectorAll('.tcat-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    render();
  }
  function filterTEffet(effet, btn) {
    activeTEffet = effet;
    document.querySelectorAll('.teffet-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    render();
  }

  // ===================== RENDER =====================
  function render() {
    const grid = document.getElementById('grid');

    if (section === 'recettes') {
      let filtered = recipes;
      if (activeType !== 'all') filtered = filtered.filter(r => r.type === activeType);
      if (activeTime !== 'all') filtered = filtered.filter(r => r.time && r.time.includes(activeTime));

      document.getElementById('count').textContent =
        filtered.length + ' recette' + (filtered.length > 1 ? 's' : '') + ' affichée' + (filtered.length > 1 ? 's' : '');

      if (filtered.length === 0) { grid.innerHTML = '<div class="empty">Aucune recette ne correspond.</div>'; return; }

      grid.innerHTML = filtered.map(r => `
        <div class="recipe">
          <div class="recipe-header">
            <div class="recipe-icon recipe-icon-${r.iconColor}">${r.icon}</div>
            <div><p class="recipe-title">${r.title}</p><p class="recipe-sub">${r.sub}</p></div>
          </div>
          ${r.blocks ? `<div class="row">${r.blocks.map(b => `<div class="block"><div class="block-label">${b.label}</div><div class="block-val">${b.val}</div></div>`).join('')}</div>` : ''}
          ${r.steps ? `<div class="how-box how-box-steps">${r.steps.map((s,i) => `<div class="step"><div class="step-num">${i+1}</div><div class="step-text">${s}</div></div>`).join('')}</div>` : ''}
          ${r.note ? `<div class="note">${r.note}</div>` : ''}
          ${r.potInfo ? `<div class="pot-info">${r.potInfo}</div>` : ''}
        </div>`).join('');

    } else {
      let filtered = tisanes;
      if (activeTCat   !== 'all') filtered = filtered.filter(t => t.cat === activeTCat);
      if (activeTEffet !== 'all') filtered = filtered.filter(t => t.effet.includes(activeTEffet));

      document.getElementById('count').textContent =
        filtered.length + ' fiche' + (filtered.length > 1 ? 's' : '') + ' affichée' + (filtered.length > 1 ? 's' : '');

      if (filtered.length === 0) { grid.innerHTML = '<div class="empty">Aucune tisane ne correspond.</div>'; return; }

      grid.innerHTML = filtered.map(t => `
        <div class="card">
          <div class="card-header"><span class="badge ${t.badgeClass}">${t.badge}</span></div>
          <div class="plant-name">${t.title}</div>
          <div class="plant-latin">${t.sub}</div>
          ${t.dosage ? `<div class="row row-tisane"><div class="block"><div class="block-label">${t.cat === 'melange' ? 'Recette' : 'Dosage frais'}</div><div class="block-val">${t.dosage}</div></div><div class="block"><div class="block-label">Infusion</div><div class="block-val">${t.infusion}</div></div></div>` : ''}
          ${t.desc ? `<div class="desc desc-tisane">${t.desc}</div>` : ''}
          ${t.note ? `<div class="note">${t.note}</div>` : ''}
          ${t.warn ? `<div class="warn">${t.warn}</div>` : ''}
        </div>`).join('');
    }
  }

  render();

